### PR TITLE
update docker-client to 8.8.1

### PR DESCRIPTION
**Pull request by mattnworb**
To fully resolve https://github.com/spotify/dockerfile-maven/issues/23

### CODE REVIEW

**Comment by dsyer** [comment]
This is kind of important, and the workaround from #23 is horrendous, so please can we have a release with this fix in it soon?

**Comment by mattnworb** [comment]
@davidxia

**Comment by mattnworb** [comment]
this is released in version 1.3.4 now.

**Comment by dsyer** [comment]
Awesome sauce! Thanks.

**Pull request merged**
