### PR TITLE
Update docker-client version to 8.14.5

### LINKED ISSUE #278: Update docker-client 8.14.5 or newer
**BUG REPORT**:

## Description

Update docker-client 8.14.5 or newer to fix issue described here https://github.com/spotify/docker-client/issues/875

The fix should be as simple as just updating the dependency version.

## How to reproduce

Run the build goal in Windows 10 similarly to what has been described here https://github.com/spotify/docker-maven-plugin/issues/351

### PR DESCRIPTION
**Pull request by lasselindqvist**
Fixes #278 

This update fixes issue described here https://github.com/spotify/docker-client/issues/875 about supporting Windows named pipes.

### CODE REVIEW

**Comment by lasselindqvist** [comment]
@mattnworb, @davidxia, any chance this could be looked at?

**Comment by lasselindqvist** [comment]
Is it possible to push the release 1.4.11 to Maven Central? I can built the release myself, but it would be nicer to have it available there.

**Comment by davidxia** [comment]
@lasselindqvist sorry for the delay. I just released 1.4.11 to Maven Central.

**Comment by lasselindqvist** [comment]
It doesn't seem to there https://mvnrepository.com/artifact/com.spotify/dockerfile-maven-plugin

**Comment by davidxia** [comment]
@mattnworb do you remember how we release this? I can get the 1.4.11-SNAPSHOT uploaded to oss.sonatype.org but not 1.4.11. I'm running `mvn clean -P release -DskipTests -Darguments=-DskipTests -Dgpg.keyname=DC90312C release:prepare release:perform --batch-mode`

**Comment by davidxia** [comment]
@lasselindqvist sorry for the delay. 1.4.11 should be here now https://search.maven.org/artifact/com.spotify/dockerfile-maven-extension/1.4.11/jar

**Pull request merged**
