### PR TITLE
Make tagging around project versions more flexible

### PR DESCRIPTION
**Pull request by drewtul**
* Add an additional parameter to tag snapshot versions of projects built into docker images as a separate tag e.g. `unstable`
* Make it possible to tag release versions as both their version number and `latest`

### CODE REVIEW

**Comment by drewtul** [comment]
I guess that's an open question, should we tag every build as `latest` when we build it, given the semantic of time only that would seem to be correct.

I guess it would make sense to tag a `SNAPSHOT` as `latest` as a release version as both `latest` and it's release number?

**Comment by drewtul** [comment]
In your example if we had a project `1.0.0-SNAPSHOT` and we went to produce a RC we might bump to `1.0.0-rc1-SNAPSHOT`, then release this as `1.0.0-rc1`, which would be tagged as that, then changing the next development version to either `1.0.0-SNAPSHOT` or `1.0.0-rc2-SNAPSHOT` that would be tagged as `latest`.

Thinking alternatively I could just remove the `-SNAPSHOT` and tag as the version number, but that doesn't feel semantically correct either.

My main goal was to avoid cluttering docker repos with ephemeral `-SNAPSHOT` images that can't be guaranteed to contain any specific version of the software as is the nature of a snapshot.

**Comment by drewtul** [comment]
@davidxia I've tried to make this more flexible by creating a `snapShotTag` value to allow you to specify a tag for snapshots rather than just latest, so you could tag your snapshots as `unstable` for example.

Additionally add a flag to configure if release versions are also tagged as latest when built, so they're both ```foo/bar:1.2.3``` and ``foo/bar:latest``.

I think this makes it more flexible for more use cases, again the default behaviour shouldn't change.

**Comment by dflemstr** [comment]
This can be decoupled from this plugin... You can use e.g. [`groovy-maven-plugin`](https://groovy.github.io/gmaven/groovy-maven-plugin/) to dynamically set a property for which tag to use and then interpolate that property in the config.  It feels like it should be done outside of this plugin at least.

**Comment by drewtul** [comment]
You're correct, it's a fair amount more config to do so than what I've proposed here, but I can see why wouldn't want to add more weight to the plugin.

**Pull request closed without merging**
