### PR TITLE
Temporary fix issue 9

### PR DESCRIPTION
**Pull request by freesoft**
Temporary fix issue 9 until we know why status have null value, also changing annotation from Nonnull to Nullable based on what's defined in ProgressMessage class.

### CODE REVIEW

**Comment by freesoft** [comment]
Can someone take a look TravisCi result? It seems related to JDK7 test environment, not related to my change.

**Comment by davidxia** [comment]
@freesoft thanks for the PR. I think Travis' oracle jdk7 is broken. See https://github.com/spotify/docker-client/pull/805 and https://github.com/travis-ci/travis-ci/issues/7964.

**Comment by davidxia** [comment]
@freesoft I just merged https://github.com/spotify/dockerfile-maven/pull/31. You can now rebase on top of master.

**Comment by freesoft** [comment]
@davidxia  The branch has updated.

**Pull request merged**
