### PR TITLE
Added support for supplying a custom Dockerfile location on build

### PR DESCRIPTION
**Pull request by npiguet**
I have a use case that requires me to have the Dockerfile in a subfolder of my maven project, but I still want to be able to ADD files and resources that are located in my projects /target folder to my image.

Therefore, I need the build mojo to support the `-f PATH` argument of `docker build`.

This changeset adds this support (with matching integration tests)

### CODE REVIEW

**Comment by npiguet** [comment]
I have no idea why the travis CI build failed... It looks unrelated to this branch. It looks like it became stuck while pulling docker images. Not sure where that could come from.

**Comment by npiguet** [comment]
Does anyone know how I can relaunch a Travis CI build? The last one looks like it failed in some infrastructure code, not in the changes in the pull request. I don't like seeing red when it should be green.

And I would really need this to be merged.

**Comment by mattnworb** [comment]
I re-triggered a build run. I believe only repo owners can do that in TravisCI, which can be a headache.

**Comment by npiguet** [comment]
Looks like it's passing. Any chance to have it merged?

**Comment by Shingaz** [comment]
We are waiting for this feature too.

**Comment by jhaeyaert** [comment]
+1 for this feature.
Is it planned to be merged ?

Thx

**Comment by tomcooperca** [comment]
+1
I'm remaining on the legacy `docker-maven-plugin` until this feature is merged in. We have one parent POM project which a number of child projects inherit from. They all use the same Dockerfile from the parent. The only way I've been able to get this plugin to perform the same behavior is to copy-pasta that parent Dockerfile into every child module due to the child build directory not being accessible to the build context. Makes for a painful process to update that Dockerfile 15+ times.

**Comment by vijay-js** [comment]
Any idea on when this is going to be merged?

**Comment by blaketsk** [comment]
+1

**Comment by cataling** [comment]
+1

**Comment by mgvazquez** [comment]
+1

**Comment by vivimice** [comment]
+1

**Comment by Trialer1** [comment]
+1

**Comment by yuelipku** [comment]
+1, this will be very helpful!

**Comment by davidgamez** [comment]
+1, any idea on when this can be merged, I found it very helpful.

**Comment by jccode** [comment]
+1

**Comment by Ellene** [comment]
+1

**Comment by phanvuliem** [comment]
+1

**Comment by hjchanna** [comment]
+1

**Comment by masterBrog** [comment]
+1 any news on this? seems to have gone quiet...

**Comment by gaurav517** [comment]
Merge it please! or if anyone knows a workaround, please share. Thanks. @mattnworb @npiguet

**Comment by Satroler** [comment]
+1

**Comment by dstanoev** [comment]
+1

**Comment by ncc0706** [comment]
+1

**Comment by habeeb-umo** [comment]
Please merge ASAP!

**Comment by php-coder** [comment]
@npiguet I see that this PR has conflict now and can't be merged (even if authors would like to do so). Are you still interesting in this PR? Could you update it? Thanks!

**Comment by juliabenatti** [comment]
+1

**Comment by jchacana** [comment]
+1. I'm staying with legacy plugin waiting for this PR :(

**Comment by cristik1991** [comment]
+1

**Comment by acoulson2000** [comment]
+1

**Comment by Bryann** [comment]
+1

**Comment by mattnworb** [comment]
sorry for the very long delay everyone. I'll try to resolve this now - had to resolve some conflicts.

**Comment by mattnworb** [comment]
not sure why Travis is not reporting status, but verified this passes all tests locally

**Comment by mattnworb** [comment]
`1.4.10` has been released with this change

**Comment by Bryann** [comment]
Thanks! :)

**Pull request merged**
