### PR TITLE
Add support for --squash experimental build option

### LINKED ISSUE #213: Adding support for option --squash in docker build
**FEATURE REQUEST**: Adding support for option --squash in docker build

## Description
Docker has an **experimental** option `--squash=true` that, once the image is built, squash the new layers into a new image with a single new layer.

Example: docker build -t image_name -f Dockerfile . --squash

### Example 1 (configuration with POM plugin):
```
<plugin>
  <groupId>com.spotify</groupId>
  <artifactId>dockerfile-maven-plugin</artifactId>
  <version>1.4.4</version>
  <executions>
    <execution>
      <id>default</id>
      <goals>
        <goal>build</goal>
        <goal>push</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <squash>true</squash>
  </configuration>
</plugin>
```

### Example 2 (configuration by command line):
`mvn dockerfile:build -Ddockerfile.build.squash`

Could you integrate this option into the plugin ?

Thanks!

### PR DESCRIPTION
**Pull request by matthyx**
Fixes #213

### CODE REVIEW

**Comment by matthyx** [comment]
Looks like a flake... how do I restart a failed build?

**Comment by matthyx** [comment]
@mattnworb or @davidxia can you have a look? I would really like to use that feature (and not rely on a snapshot for that).

**Comment by matthyx** [comment]
@davidxia thanks a lot, let me update that this afternoon.

**Comment by matthyx** [comment]
@davidxia will you have time this week?

**Comment by davidxia** [comment]
Sorry for the delay. Thanks for the reminder. LGTM!

**Pull request merged**
