### PR TITLE
#308 Extend repository validation by allowing port number.

### PR DESCRIPTION
**Pull request by mmaeller**
Adjusted regex validation to allow port number.

### CODE REVIEW

**Comment by mmaeller** [comment]
You're right, I changed it accordingly.

**Comment by stephanedaviet** [comment]
You got a problem of automatic formatting on the file `TestRepoNameValidation` at lines 10 and 12: the end of line spaces have been stripped. Thus the header license check test in Travis fails. You should fix it so that the PR became mergeable.

Note, I comment because we are also interested in this fix ;-).

**Comment by mmaeller** [comment]
Thx @stephanedaviet , fixed 👍

**Comment by rbdiang** [comment]
The port validation rule is also tipping me up.  We push to a private docker registry listening on a different port.  When will this fix be merged and available in maven central?

**Comment by wendro** [comment]
Can it land in snapshots - soon?

**Comment by cvgaviao** [comment]
Hey, could some maintainer to merge this fix, please ?

**Comment by mattnworb** [comment]
I've released v1.4.13 with this change, I'll update the changelog shortly. Thanks again for the PR.

**Pull request merged**
